name: patch-forensics
channels:
  - pytorch
  - ostrokach-forge
  - conda-forge
dependencies:
  - python=3.6
  - cudatoolkit=10.1
  - cudnn=7.6.0
  - pytorch=1.4
  - torchvision
  - albumentations
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - seaborn
  - jupyter
  - oyaml
  - opencv
  - tqdm
  - pip
  - pillow
  - tensorboard
  - tensorboardX
  - pip:
    - dill
    - gdown

